.TH MFTRACE 1 "April 5, 2004"
.
.
.SH NAME
mftrace \- convert METAFONT format fonts into Type1 outline fonts
.
.
.SH SYNOPSIS
.B mftrace
.RI [ options ] " fontname"
.
.
.SH DESCRIPTION
.B mftrace
is a program that can convert a METAFONT font into a Type1 font.  It
is simply called with the name of the font (without a .mf suffix) and
produces a Type1 font file called either
.IR \%fontname .pfa
or
.IR \%fontname .pfb
depending on the command line options.
.P
For tracing the bitmap,
.B mftrace
either uses
.B potrace
or
.B autotrace
(the former preferred) if available; this can be overridden with the
.B \%\-\-autotrace
and
.B \%\-\-potrace
command line options.
.
.
.SH OPTIONS
This program follows the usual GNU command line syntax, with long
options starting with two dashes (`-').
.
.TP
.BR \-k , \-\-keep
Keep all output in directory `mftrace.dir'.
.
.TP
.BI \-\-magnification= MAG
The magnification to use for the PFA file. The default is 1000. The
larger the magnification, the more precise the PFA file will
be. However, when the magnification is too large METAFONT can crash
with overflow errors.
.PP
Sadly, many MF fonts contain resolution checks
.sp
.RS
    if dots_per_inch * design_size > 1500:
.RE
.sp
This check is susceptible to overflow errors.  Such code should be
reported as a bug, and changed to
.sp
.RS
    if dots_per_inch > (1500 / design_size):
.RE
.sp
.
.TP
.BI \-\-formats= FMT1,FMT2,...
Specify which formats to generate (default is pfa).  Choices are: afm,
pfa, pfb, ttf, svg.  Note that
.B \%fontforge
(formerly called
.BR \%pfaedit )
must be installed to generate any format other than pfa.
.
.TP
.B \-\-simplify
This will pass the created Type1 font through
.B \%fontforge
(formerly called
.BR \%pfaedit )
to simplify and autohint it.
.
.TP
.BI \-\-gffile= FILE
Use generic font file
.I FILE
instead of running Metafont.
.
.TP
.BR \-I " " \fIDIR\fP ", " \-\-include= \fIDIR\fP
Add
.I DIR
to the current path for searching files.
.
.TP
.BI \-\-glyphs= LIST
Process only these glyphs.
.I LIST
is a comma separated list of decimal numbers or ranges, for example
1-10,50,55,90-100.
.
.TP
.BI \-\-tfmfile= FILE
Use
.I FILE
for the TFM file.  (The default is to use
.IR \%fontname .tfm).
.
.TP
.BR \-e " " \fIENC\fP ", " \-\-encoding=\fIENC\fP
Use encoding file
.IR ENC .
.B mftrace
will try to determine the encoding file automatically, from the
encoding specified in the TFM file, the default being tex256.enc.
.
.TP
.B \-\-keep-trying
Try to continue if autotrace fails: first try it with a less smoothed
curve, and if that fails, skip the character.  By default
.B mftrace
leaves a file `trace-bug-\fIfont\fP-\fIchar\fP.pbm' and stops the process
with a request to file a bugreport.
.
.TP
.B \-\-dos-kpath
Try to use MikTeX's version of
.B kpsewhich.
.
.TP
.B \-\-potrace
Use
.B potrace
for tracing bitmaps.  The default is to use
.B potrace
if it is found, otherwise to use
.BR autotrace .
.
.TP
.B \-\-autotrace
Use
.B autotrace
for tracing bitmaps.
.
.TP
.B \-\-no-afm
Don't read the AFM file to find font information.
.
.TP
.B \-\-noround
Do not round coordinates of control points to integer values (use with
.BR \-\-grid ).
Disabled by default.
.
.TP
.BI \-\-grid= GRID
Set reciprocal grid size in em units multiplied by ratio
magnification/1000.  For example, \fB\-\-grid\fP 10
\fB\-\-magnification\fP 1000 will round coordinates of control points
to 1/10 of em unit.  Useful simultaneously with the \fB\-\-noround\fB
option.  Default \fIGRID\fP value is 1, i.e., round to integer.  This
option is only used with
.BR potrace .
.
.TP
.B \-V, \-\-verbose
Be verbose.
.
.TP
.B \-h, \-\-help
Show summary of options.
.
.TP
.B \-v, \-\-version
Show version of program.
.
.TP
.B \-w, \-\-warranty
Show warranty and copyright.
.
.
.SH "SEE ALSO"
.BR mf (1),
.BR autotrace (1),
.BR potrace (1),
.BR fontforge (1).
.
.
.SH AUTHOR
.B mftrace
was written by Han-Wen Nienhuys <hanwen@cs.uu.nl>.
This manual page was originally written by Julian Gilbey <jdg@debian.org>
and has been revised by Werner Lemberg <wl@gnu.org>.
.
.\" EOF
