.TH MFTRACE 1 "February 11, 2002"
.SH NAME
mftrace \- convert METAFONT format fonts into Type1 outline fonts
.SH SYNOPSIS
.B mftrace
.RI [ options ] " fontname"
.SH DESCRIPTION
.B mftrace
is a program that can convert a METAFONT font into a Type1 font.  It
is simply called with the name of the font (without a .mf suffix) and
produces a Type1 font file called either
.IR fontname .pfa
or
.IR fontname .pfb
depending on the command line options.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
.TP
.B \-k, \-\-keep
Keep all output in directory `mftrace.dir'.
.TP
.BI \-\-glyphs LIST
Process only these glyphs.
.I LIST
is a comma separated list of glyphs.
.TP
.B \-a, \-\-pfa
Generate a PFA file (default).
.TP
.B \-b, \-\-pfb
Generate a PFB file.
.TP
.BI \-\-tfmfile= FILE
Use
.I FILE
for the TFM file.  (The default is to use
.IR fontname .tfm).
.TP
.BI "\-o, \-\-output-base=" FILE
Output to
.IR FILE .pfa
or
.IR FILE .pfb.
.TP
.BI "\-e, \-\-encoding=" ENC
Use encoding file
.IR ENC .
(The default is to use tex256.enc.)
.TP
.B \-\-keep-trying
Try to continue if autotrace fails: first try it with a less smoothed
curve, and if that fails, skip the character.  By default mftrace
leaves a file `autotrace-bug-font-char.pbm' and stops the process with
a request to file a bugreport.
.TP
.B \-V, \-\-verbose
Be verbose.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-\-simplify
This will pass the created Type1 font through \fBpfaedit\fR to
simplify and autohint it.
.TP
.B \-v, \-\-version
Show version of program.
.TP
.B \-w, \-\-warranty
Show warranty and copyright.
.SH "SEE ALSO"
.BR mf (1),
.BR autotrace (1).
.SH AUTHOR
.B mftrace
was written by Han-Wen Nienhuys <hanwen@cs.uu.nl>.
This manual page was written by Julian Gilbey <jdg@debian.org>,
for the Debian GNU/Linux system (but may be used by others).

THIS MANUAL PAGE IS OUTDATED.
